# Recipient Recommender

This notebook contains the implementation of a recommender that recommends recipients to a Grant-Writer.

In [113]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import pickle

In [114]:
# input Grant Writer preferences
inp = np.empty([18])
fields = list(pd.read_csv("kiva_loans.csv//recep_data.csv").columns)
for i in fields:
    inp[fields.index(i)] = input(i+': ')
print(inp)

loan_amount: 1500
Services: 0
Clothing: 0
Transportation: 0
Personal Use: 0
Retail: 0
Health: 1
Food: 0
Education: 1
Manufacturing: 0
Wholesale: 0
Construction: 0
Arts: 0
Agriculture: 0
Entertainment: 0
Housing: 0
male: 0
female: 1
[1.5e+03 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00 0.0e+00 1.0e+00
 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00]

In [115]:
# # normalize grant amount
# df_norm = pd.read_csv("kiva_loans.csv//kiva_loans.csv")
# df_norm = df_norm[df_norm['country_code'] == 'IN']
# inp[0] = (inp[0] - df_norm['loan_amount'].min())/(df_norm['loan_amount'].max() - df_norm['loan_amount'].min())
# print(inp[0])

In [116]:
len(fields)

18

In [117]:
# load classifier and classify input
clf = pickle.load(open("kiva_loans.csv//clf_lender.p", "rb"))
cluster = clf.predict(inp.reshape(1, -1))
print(cluster)

[9]

In [118]:
# load the cluster distances table
cluster_dist_tab = np.load(open("kiva_loans.csv//cluster_dist_tab.npy", "rb"))

In [119]:
# calculate cluster nearest to input's cluster
print(cluster_dist_tab[:, cluster])
nearest_cluster = np.where(cluster_dist_tab[:, cluster] == np.amin(cluster_dist_tab[:, cluster]))
print(nearest_cluster[0][0])

[[  363.9701872 ]
 [ 2548.38967594]
 [  670.94606067]
 [ 3233.28549106]
 [ 1577.06064959]
 [12924.95218808]
 [ 4395.02790272]
 [  211.23151986]
 [ 2095.61751422]
 [ 1116.64164245]]
7

In [120]:
# read recipient data
df = pd.read_csv("kiva_loans.csv//recep_data.csv")
labels = pd.read_csv("kiva_loans.csv//recep_labels.csv")
df['labels'] = labels

In [121]:
# calculate distances from input of all points within nearest cluster  
df = df[df['labels'] == nearest_cluster[0][0]].loc[:, df.columns != 'labels']
df['dists'] = np.linalg.norm(df[df.columns] - inp)

In [122]:
# sort points in ascending order of distance from input
df.sort_values(by=['dists']).loc[:, df.columns != 'dists'].iloc[:20]

,loan_amount,Services,Clothing,Transportation,Personal Use,Retail,Health,Food,Education,Manufacturing,Wholesale,Construction,Arts,Agriculture,Entertainment,Housing,male,female
0,150.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7235,150.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
7236,225.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
7239,225.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7242,225.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7243,225.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
7245,225.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7250,225.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7254,225.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7259,225.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7262,225.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
7269,250.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7270,225.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
7276,250.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
7278,250.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7279,250.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7280,250.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
7287,250.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
7290,250.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
7291,175.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1